// Generated by https://quicktype.io

export interface Cita {
    idCita:      null;
    nomCliente:  string;
    hora:        string;
    dia:         string;
    servicio:    string;
    nomServicio: string;
}

